name: Rollback to Previous Site Version

on:
  workflow_dispatch:
    inputs:
      confirm_rollback:
        description: 'Type "CONFIRM" to proceed with rolling back to the previous version of the site'
        required: true
        type: string
      rollback_steps:
        description: 'How many deployments to roll back (usually 1 for previous version)'
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'
        default: '1'

jobs:
  find-deployments:
    runs-on: ubuntu-latest
    outputs:
      deployment_sha: ${{ steps.find-deployment.outputs.deployment_sha }}
      current_version: ${{ steps.get-info.outputs.current_version }}
      rollback_version: ${{ steps.get-info.outputs.rollback_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 100  # Fetch enough history to find previous deployments

      - name: Check confirmation code
        run: |
          if [ "${{ github.event.inputs.confirm_rollback }}" != "CONFIRM" ]; then
            echo "Error: You must type 'CONFIRM' to proceed with the rollback."
            echo "This is to prevent accidental rollbacks."
            exit 1
          fi

      - name: Find deployment commits
        id: find-deployment
        run: |
          # Simply use the most recent commits for reliable rollback
          # This ensures we roll back to exactly the nth previous commit
          echo "Getting recent commit history..."
          RECENT_COMMITS=$(git log -n 10 --pretty=format:"%H %s")
          
          echo "Recent commits (will select based on rollback steps):"
          echo "$RECENT_COMMITS"
          
          # How many steps back to go based on user input
          STEPS_BACK=${{ github.event.inputs.rollback_steps }}
          
          # Get the commit SHA for the deployment we want to roll back to
          # Using NR==STEPS_BACK+1 to get the commit that's exactly STEPS_BACK before the current one
          ROLLBACK_SHA=$(echo "$RECENT_COMMITS" | awk "NR==$((STEPS_BACK+1)) {print \$1}")
          
          if [ -z "$ROLLBACK_SHA" ]; then
            echo "Error: Could not find a deployment to roll back to."
            echo "Available commit history:"
            git log -n 10 --pretty=format:"%H %s"
            exit 1
          fi
          
          echo "deployment_sha=$ROLLBACK_SHA" >> $GITHUB_OUTPUT
          echo "Found rollback target: $ROLLBACK_SHA"

      - name: Get version information
        id: get-info
        run: |
          # Get current version info
          CURRENT_COMMIT=$(git rev-parse HEAD)
          CURRENT_DATE=$(git show -s --format=%ci $CURRENT_COMMIT)
          CURRENT_MESSAGE=$(git show -s --format=%s $CURRENT_COMMIT)
          echo "current_version=$CURRENT_MESSAGE ($CURRENT_DATE)" >> $GITHUB_OUTPUT
          
          # Get rollback version info
          ROLLBACK_SHA="${{ steps.find-deployment.outputs.deployment_sha }}"
          ROLLBACK_DATE=$(git show -s --format=%ci $ROLLBACK_SHA)
          ROLLBACK_MESSAGE=$(git show -s --format=%s $ROLLBACK_SHA)
          echo "rollback_version=$ROLLBACK_MESSAGE ($ROLLBACK_DATE)" >> $GITHUB_OUTPUT
          
          echo "Current version: $CURRENT_MESSAGE ($CURRENT_DATE)"
          echo "Rolling back to: $ROLLBACK_MESSAGE ($ROLLBACK_DATE)"

  confirm-rollback:
    needs: find-deployments
    runs-on: ubuntu-latest
    steps:
      - name: Display rollback information
        run: |
          echo "=== SITE ROLLBACK SUMMARY ==="
          echo "Current version: ${{ needs.find-deployments.outputs.current_version }}"
          echo "Rolling back to: ${{ needs.find-deployments.outputs.rollback_version }}"
          echo "============================="
          
          # Final confirmation check
          if [ "${{ github.event.inputs.confirm_rollback }}" != "CONFIRM" ]; then
            echo "Error: Confirmation failed. Rollback aborted."
            exit 1
          fi
          
          echo "Proceeding with rollback..."

  rollback-site:
    needs: [find-deployments, confirm-rollback]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 100  # Need enough history to go back to the target commit
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Reset to previous version
        run: |
          echo "Resetting to previous version at commit: ${{ needs.find-deployments.outputs.deployment_sha }}"
          
          # Setup Git identity for the commit
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Rollback Action"
          
          # Commit message describes the rollback
          ROLLBACK_MSG="Rollback to previous site version: ${{ needs.find-deployments.outputs.rollback_version }}"
          
          # Make sure we have the full history
          git fetch --unshallow || true
          
          # Get current commit hash for comparison
          CURRENT_SHA=$(git rev-parse HEAD)
          TARGET_SHA="${{ needs.find-deployments.outputs.deployment_sha }}"
          
          echo "Current commit: $CURRENT_SHA"
          echo "Target commit: $TARGET_SHA"
          
          # Check if we're already at the target commit
          if [ "$CURRENT_SHA" = "$TARGET_SHA" ]; then
            echo "Already at the target commit. No changes needed."
            exit 0
          fi
          
          # Instead of direct force push, create a selective content rollback
          # This avoids the workflow permissions issue
          echo "Creating rollback content using git archive and checkout"
          
          # Create a temporary branch
          TEMP_BRANCH="rollback-$(date +%Y%m%d%H%M%S)"
          git checkout -b $TEMP_BRANCH
          
          # Get list of files from target commit, excluding workflow files
          echo "Extracting files from target commit (excluding workflow files)..."
          mkdir -p /tmp/rollback_content
          git archive --format=tar $TARGET_SHA | (cd /tmp/rollback_content && tar xf -)
          
          # First remove all current files (except .git and workflows directory)
          echo "Removing current files (except workflows)..."
          find . -type f -not -path "./.git/*" -not -path "./.github/workflows/*" -delete
          
          # Copy back the files from the target commit
          echo "Copying files from target commit..."
          cp -rf /tmp/rollback_content/* .
          
          # Add all changes
          git add -A
          
          # Commit the changes
          git commit -m "$ROLLBACK_MSG"
          
          # Push the changes to the main branch
          echo "Pushing rollback changes to main branch"
          git push origin $TEMP_BRANCH:main
          
          echo "Successfully rolled back to content from commit: $TARGET_SHA"
          echo "Rollback description: ${{ needs.find-deployments.outputs.rollback_version }}"
      
      - name: Trigger deployment
        run: |
          echo "Triggering deployment of the rolled-back version..."
          # The deployment will happen automatically when changes are pushed to main
          
      - name: Rollback complete
        run: |
          echo "✅ Rollback complete!"
          echo "The site has been restored to the previous version."
          echo "Previous version: ${{ needs.find-deployments.outputs.rollback_version }}"

